# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c645db1a70675d942928a1b3c8352b8a0b2f41e9ba82dc2eae98ac23fb816150842daf7c3e864285a73ec378e899d31fbacf624e06343fa2e5b51c6c9608e63e

test:
  secret_key_base: 0a78f689fb035dafe4a16dbf60080b2bd0e215f4a2271185ea9b87f072397bf385bb4589de117117513ff3fdfe47ad84a6b813f6f57936668ad11acbe18cee45

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
